import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import { Noto_Sans_Thai} from "next/font/google";
 
const noto_sans_thai = Noto_Sans_Thai({ subsets: ["latin"]
  
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
     
      <html lang="en">
      <body>
        {/* Layout UI */}
        <NavBar />
      <main className={`${noto_sans_thai}`}>{children}</main>
      <Footer />
      </body>
    </html>
      
      
    
  );
}
